apiVersion: apps/v1
kind: Deployment
metadata:
  name: lib-backend
  namespace: library
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lib-backend
  template:
    metadata:
      labels:
        app: lib-backend
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: backend
        image: ghcr.io/peacdo/lib-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@postgres-service:5432/library
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: lib-secrets
              key: jwt-secret
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: library
spec:
  selector:
    app: lib-backend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP