apiVersion: apps/v1
kind: Deployment
metadata:
  name: lib-frontend
  namespace: library
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lib-frontend
  template:
    metadata:
      labels:
        app: lib-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/peacdo/lib-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: library
spec:
  selector:
    app: lib-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP 