apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: library
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30= # This is base64 encoded "{}" as a placeholder
# Secret is created by GitHub Actions