apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lib-ingress
  namespace: library
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: tahir.abi
    http:
      paths:
      - path: /lib(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80 