apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lib-ingress
  namespace: library
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: staj.com
    http:
      paths:
      - path: /lib/api/
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80 