name: CI/CD Pipeline

permissions:
  contents: read
  packages: write
  id-token: write
  actions: write

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REGISTRY: ghcr.io/peacdo
  KUBE_NAMESPACE: library

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      # ... existing steps ...

      - name: Setup Kubernetes Config
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          
          # Create namespace if not exists
          kubectl create namespace library --dry-run=client -o yaml | kubectl apply -f -

      - name: Create Secrets
        run: |
          export KUBECONFIG=kubeconfig.yaml
          
          # Create JWT secret
          kubectl create secret generic lib-secrets \
            --namespace library \
            --from-literal=jwt-secret=${{ secrets.JWT_SECRET }} \
            --dry-run=client -o yaml | kubectl apply -f -
          
          # Create image pull secret
          kubectl create secret docker-registry ghcr-secret \
            --namespace library \
            --docker-server=ghcr.io \
            --docker-username=peacdo \
            --docker-password=${{ secrets.GHCR_PAT }} \
            --dry-run=client -o yaml | kubectl apply -f -
        
      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG=kubeconfig.yaml
          
          # Apply k8s manifests except secrets
          kubectl apply -f k8s/backend-deployment.yaml -f k8s/frontend-deployment.yaml -f k8s/ingress.yaml -f k8s/postgres.yaml
          
          # Wait for resources
          kubectl wait --for=condition=ready pods --all -n library --timeout=5m